### ISSUE TITLE
Design: デザインカンプの作成

### ISSUE THREAD

**Issue by t-k-satoh** [t-k-satoh/take_two#1]
## 概要
- デザインカンプの作成

## 目的
- デザインの方向性の確認

## 成果物
デザインの方向性が確認できるものならなんでも
- ワイヤーフレーム
- コンセプトの箇条書き
- ラフスケッチ

など

**Comment by t-k-satoh** [comment]
@taketakeflower 
このIssue にコメントでデザインを提出してください。  
https://github.com/t-k-satoh/take_two/issues/4  のように一つ一つ添付されると確認時間がかかるので、zip で圧縮して添付をお願いします。

**Comment by taketakeflower** [comment]
[idea.zip](https://github.com/t-k-satoh/take_two/files/2706756/idea.zip)

**Comment by t-k-satoh** [comment]
@taketakeflower 
確認しました。  
ちょっと量が多い(コーディングが重そう。。。)かと思うのですが、後々削るところを考えつつ  
全体のスケジュールに影響が出ないようにしてください。

**Comment by taketakeflower** [comment]
![1_0113](https://user-images.githubusercontent.com/45894447/51084335-fec7f400-176a-11e9-9656-34a54406c6d3.jpg)

**Comment by taketakeflower** [comment]
[_____1_0113.zip](https://github.com/t-k-satoh/take_two/files/2753001/_____1_0113.zip)
