### ISSUE TITLE
アイディアスケッチ

### ISSUE THREAD

**Issue by taketakeflower** [t-k-satoh/take_two#4]
アイディアスケッチ
[B-1_3.pdf](https://github.com/t-k-satoh/take_two/files/2703482/B-1_3.pdf)
[B-1_31.pdf](https://github.com/t-k-satoh/take_two/files/2703484/B-1_31.pdf)
[B-1_313.pdf](https://github.com/t-k-satoh/take_two/files/2703485/B-1_313.pdf)
[B-1_3138.pdf](https://github.com/t-k-satoh/take_two/files/2703486/B-1_3138.pdf)
[B-1_3138のコピー.pdf](https://github.com/t-k-satoh/take_two/files/2703487/B-1_3138.pdf)
[Uploading B-1_3139.pdf…]()
[Uploading B-1_3139のコピー.pdf…]()
[Uploading B-1_3140.pdf…]()
[Uploading B-1_3141.pdf…]()
[Uploading B-1_3142.pdf…]()
[Uploading B-1_3143.pdf…]()
[Uploading B-1_3144.pdf…]()
[Uploading B-1_3145.pdf…]()
[Uploading B-1_3146.pdf…]()

**Comment by taketakeflower** [comment]
[B-1_3146.pdf](https://github.com/t-k-satoh/take_two/files/2703501/B-1_3146.pdf)
[B-1_3146のコピー.pdf](https://github.com/t-k-satoh/take_two/files/2703502/B-1_3146.pdf)
[B-1_3146のコピー.pdf](https://github.com/t-k-satoh/take_two/files/2703504/B-1_3146.pdf)
[Uploading B-1_3147のコピー.pdf…]()
[Uploading B-1_3148.pdf…]()
[B-1_3147.pdf](https://github.com/t-k-satoh/take_two/files/2703506/B-1_3147.pdf)
[Uploading B-1_3149.pdf…]()
[Uploading B-1_3150.pdf…]()
[Uploading B-1_3151.pdf…]()
[Uploading B-1_3152.pdf…]()

**Comment by taketakeflower** [comment]
[Uploading B-1_3154.pdf…]()
[Uploading B-1_3155.pdf…]()
[Uploading B-1_3152のコピー.pdf…]()
[Uploading B-1_3153.pdf…]()
[Uploading B-1_3153のコピー.pdf…]()
[Uploading B-1_3154.pdf…]()
[Uploading B-1_3155.pdf…]()

**Comment by t-k-satoh** [comment]
一旦、このIssue を閉じます
